'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class callback

    '''<summary>
    '''mCatID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mCatID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''div_properties control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_properties As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''callbackPanelX control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents callbackPanelX As Global.DevExpress.Web.ASPxCallbackPanel.ASPxCallbackPanel

    '''<summary>
    '''PanelContent1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelContent1 As Global.DevExpress.Web.ASPxPanel.PanelContent

    '''<summary>
    '''cmb_source_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmb_source_type As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''sql_source_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sql_source_type As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''cmb_group_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmb_group_type As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''sql_group_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sql_group_type As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''Category control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Category As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''CategoryHidden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CategoryHidden As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''SubCategoryI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubCategoryI As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''SubCatI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubCatI As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''SubCategoryII control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubCategoryII As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''SubCatII control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubCatII As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''SubCategoryIII control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubCategoryIII As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''cmb_priority control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmb_priority As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''sql_priority control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sql_priority As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''cmb_severity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmb_severity As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''sql_severity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sql_severity As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''cmb_status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmb_status As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''sql_status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sql_status As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SourceType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SourceType As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''GroupType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GroupType As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SourceCategori control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SourceCategori As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SourceCategoriI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SourceCategoriI As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SourceCategoriII control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SourceCategoriII As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SourceCategoriIII control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SourceCategoriIII As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''DSHistoryAgent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSHistoryAgent As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''DSCustHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSCustHistory As Global.System.Web.UI.WebControls.SqlDataSource
End Class
