'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class emai_setting

    '''<summary>
    '''div_alltwt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_alltwt As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txt_acc_email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_acc_email As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rqr_acc_email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rqr_acc_email As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txt_acc_password control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_acc_password As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rqr_acc_pass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rqr_acc_pass As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txt_acc_smtp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_acc_smtp As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rqr_acc_smtp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rqr_acc_smtp As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txt_port control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_port As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rqr_acc_port control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rqr_acc_port As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Btn_Simpan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Simpan As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''Btn_Cancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Cancel As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
