'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class email_address

    '''<summary>
    '''div_email_address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_email_address As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''GRmEmailSuzuki control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GRmEmailSuzuki As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''sql_email_address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sql_email_address As Global.System.Web.UI.WebControls.SqlDataSource
End Class
