'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class facebook_keyword

    '''<summary>
    '''txtsentimen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsentimen As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnsubmitkey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnsubmitkey As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnupdatekey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnupdatekey As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''show control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents show As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''DD1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DsDropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DsDropdown As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''txtsub control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsub As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnsubmitsub control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnsubmitsub As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnupdatesub control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnupdatesub As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''bukadeh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bukadeh As Global.System.Web.UI.WebControls.Literal
End Class
