'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class inbox_todolist

    '''<summary>
    '''lbl_jumlah_todolist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_jumlah_todolist As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''div_table control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_table As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ltr_email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltr_email As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''div_compose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_compose As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txt_to control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_to As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ASPxHtmlEditor1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxHtmlEditor1 As Global.DevExpress.Web.ASPxHtmlEditor.ASPxHtmlEditor
End Class
