'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MasterBackup

    '''<summary>
    '''div_menu_dashboard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_menu_dashboard As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div_menu_master_table control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_menu_master_table As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''A1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A1 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''div_master_Transaction_Type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_master_Transaction_Type As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div_master_calltypeone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_master_calltypeone As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''a_brand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a_brand As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''div_master_calltypetwo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_master_calltypetwo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div_master_calltypetre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_master_calltypetre As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div_master_sourcetype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_master_sourcetype As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div_master_grouptype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_master_grouptype As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div_master_status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_master_status As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div_master_karyawan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_master_karyawan As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div_master_email_alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_master_email_alert As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div_master_email_address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_master_email_address As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div_menu_customer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_menu_customer As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div_menu_todolist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_menu_todolist As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div_menu_channel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_menu_channel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div_channel_twitter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_channel_twitter As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div_twitter_history control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_twitter_history As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div_twitter_keyword_setting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_twitter_keyword_setting As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div_channel_facebook control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_channel_facebook As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div_facebook_history control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_facebook_history As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div_facebook_keyword_setting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_facebook_keyword_setting As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div_channel_email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_channel_email As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div_channel_sms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_channel_sms As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div_channel_fax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_channel_fax As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div_channel_chat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_channel_chat As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div_Sentimen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_Sentimen As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Li2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Li2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Li3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Li3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div_menu_ticket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_menu_ticket As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div_ticket_create control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_ticket_create As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div_ticket_todolist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_ticket_todolist As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div_ticket_assign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_ticket_assign As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div_ticket_history control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_ticket_history As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div_menu_Management_user control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_menu_Management_user As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div_user_add control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_user_add As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div_user_setting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_user_setting As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div_menu_report control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_menu_report As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div_report_satu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_report_satu As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div_report_dua control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_report_dua As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div_menu_grafik control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_menu_grafik As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div_menu_knowledge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_menu_knowledge As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
