'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class report_transaksi

    '''<summary>
    '''div_calltype_one control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_calltype_one As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div_ticket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_ticket As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''cbChannelTransaksi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbChannelTransaksi As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''dsChannelTransaksi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsChannelTransaksi As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''cbJenisTransaksi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbJenisTransaksi As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''dsJenisTransaksi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsJenisTransaksi As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''cbUnitKerja control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbUnitKerja As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''dsUnitKerja control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsUnitKerja As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''cbSubject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbSubject As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''dsSubject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsSubject As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''cbStatusTransaksi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbStatusTransaksi As Global.DevExpress.Web.ASPxEditors.ASPxComboBox
End Class
