'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Transaction_Type

    '''<summary>
    '''div_transaction_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_transaction_type As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''gv_transaction_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_transaction_type As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''sql_transaction_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sql_transaction_type As Global.System.Web.UI.WebControls.SqlDataSource
End Class
