'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class user_sett

    '''<summary>
    '''div_calltype_one control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_calltype_one As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div_ticket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_ticket As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''gridLevelUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridLevelUser As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''div_new control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_new As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txt_level_user control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_level_user As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''KodeLevelUserSbg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents KodeLevelUserSbg As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''txt_description control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_description As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''sql_user control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sql_user As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sql_user_level control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sql_user_level As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sql_muser_trustee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sql_muser_trustee As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sql_level_user control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sql_level_user As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''callbackPanelX control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents callbackPanelX As Global.DevExpress.Web.ASPxCallbackPanel.ASPxCallbackPanel

    '''<summary>
    '''PanelContent2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelContent2 As Global.DevExpress.Web.ASPxPanel.PanelContent

    '''<summary>
    '''txtGroupID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGroupID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''checkBoxList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents checkBoxList As Global.DevExpress.Web.ASPxEditors.ASPxCheckBoxList

    '''<summary>
    '''Btn_Add control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Add As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Btn_Update control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Update As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Btn_Save control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Save As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Btn_Cancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Cancel As Global.System.Web.UI.WebControls.Button
End Class
